config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'users/index'
  root to: "rooms#index"
  resources :users, only: [:index]
  resources :rooms, only: [:index, :new, :create] do
    collection do
      get 'search'
    end
    resources :messages, only: [:index,:create]
  end
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '経済' },
    { id: 3, name: '政治' },
    { id: 4, name: '地域' },
    { id: 5, name: '国際' },
    { id: 6, name: 'IT' },
    { id: 7, name: 'エンタメ' },
    { id: 8, name: 'スポーツ' },
    { id: 9, name: 'グルメ' },
    { id: 10, name: 'その他' }
  ]
  include ActiveHash::Associations
  has_many :room
end

app/models/message.rb
class Message < ApplicationRecord

  with_options presence: true do
    validates :content
  end

  belongs_to :room
  belongs_to :user
end

app/models/referee.rb
class Referee < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :voting

  validates :voting_id, numericality: { other_than: 1 }
end

app/models/room.rb
class Room < ApplicationRecord

  with_options presence: true do
    validates :name, length: { maximum: 50 }
    validates :explanation, length: { maximum: 256 }
    validates :category_id, numericality: { other_than: 1 }
    validates :image
  end
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  has_many :room_users
  has_many :users, through: :room_users
  has_many :messages
  has_one_attached :image

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    validates :password
    validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  end
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
end

app/models/voting.rb
class Voting < ActiveHash::Base
  self.data = [
    { id: 1, name:'__' },
    { id: 2, name: '○'},
    { id: 3, name: '☓'}
  ]
  include ActiveHash::Associations
  has_many :referees
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    unless user_signed_in?
      redirect_to new_user_registration_path
    end
    @message = Message.new
    @room = Room.find(params[:room_id])
    @rooms = Room.all
    @messages = @room.messages.includes(:user).order(id: "DESC")
  end
  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user).order(id: "DESC")
      render :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:content).merge(user_id: current_user.id)
  end
end

app/controllers/referees_controller.rb
class RefereesController < ApplicationController
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_q, only: [:index, :search,:new]
  def index
    @user = User.all

     @rooms = Room.page(params[:page]).per(9).order(id: "DESC")
  end

  def new
    unless user_signed_in?
      redirect_to  new_user_registration_path
    end
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      @q = Room.ransack(params[:q])
      render :new
    end
  end
  def search 
    @results = @q.result(distinct: true)
  end

  private
  def room_params
    params.require(:room).permit(:name,:explanation,:category_id,:image)
  end

  def set_q
    @q = Room.ransack(params[:q])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/referees_helper.rb
module RefereesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DebateApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>  
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>

  </head>



  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="container scrol ming">

<h3 class=" text-center "><%=@room.name%> </h3>
<div class="messaging">
    <div class="inbox_msg pt-3" ,id= "scroll">
        <div class="msg_history">
        
      <% @messages.each do |message|%>
      <% if @messages.present? %>
          <% if current_user.id == message.user_id %>
              <div class="received_msg">
                <div class="received_withd_msg">
                  <p><%=message.content%></p>
                  <div class="time_date"> <%=message.created_at.to_s(:datetime_jp)%>    |   <%=message.user.nickname%> </div>
                </div>
              </div>
          <% else %>
            <div class="outgoing_msg">
              <div class="sent_msg">
                <p><%=message.content%></p>
                <div class="time_date"> <%=message.created_at.to_s(:datetime_jp)%>    |    <%=message.user.nickname%>  </div>
              </div>
            </div>
          <%end%>
        <%end%>
      <%end%>
        </div>
    </div>

  <div class="alert alert-danger text-center" role="alert">
  ⚠マナーを守って楽しくチャットしましょう。！！
</div>
</div>

app/views/messages/_message.html.erb
          <div class="type_msg">
            <div class="input_msg_write">
              <%= form_with model: [@room, @message], local: true do |f|%>
                    <%= render 'devise/shared/error_messages', model: f.object %>
                <i class="fas fa-search mr-3" style="color: royalblue;"></i><%= f.text_area :content, class: 'form-control' , placeholder: 'type a messaage' %>
                <i class="fa fa-paper-plane-o" aria-hidden="true"></i><i class="fas fa-paper-plane"></i><%= f.submit '送信', class: 'btn btn-primary' %>
                <% end %>
            </div>
          </div>
          <div class="text-center">
            <h4>この部屋の説明</h4>
            <p class="wrap"><%= @room.explanation %></p>
          </div>

app/views/messages/index.html.erb
+<head>
    <style>
    .container{max-width:1170px; 
    margin:auto;

    }
img{ max-width:100%;}

.inbox_msg {
  border: 1px solid #c4c4c4;
  clear: both;
  overflow: hidden;
}





.received_msg {
  display: inline-block;
  padding: 0 0 0 10px;
  vertical-align: top;
  width: 92%;
 }
 .received_withd_msg p {
  background: #ebebeb none repeat scroll 0 0;
  border-radius: 3px;
  color: #646464;
  font-size: 14px;
  margin: 0;
  padding: 5px 10px 5px 12px;
  width: 100%;
}
.time_date {
  color: #747474;
  display: block;
  font-size: 12px;
  margin: 8px 0 0;
}
.received_withd_msg { width: 57%;}
.mesgs {
  float: left;
  padding: 30px 15px 0 25px;
  width: 60%;
  height: 500px;
  overflow: scroll;

}


 .sent_msg p {
  background: #05728f none repeat scroll 0 0;
  border-radius: 3px;
  font-size: 14px;
  margin: 0; color:#fff;
  padding: 5px 10px 5px 12px;
  width:100%;
}
.outgoing_msg{ overflow:hidden; margin:26px 0 26px;}
.sent_msg {
  float: right;
  width: 46%;
}
.input_msg_write input {
  background: rgba(0, 0, 0, 0) none repeat scroll 0 0;
  border: medium none;
  color: #4c4c4c;
  font-size: 15px;
  min-height: 48px;
  width: 100%;
}

.type_msg {border-top: 1px solid #c4c4c4;position: relative;}
.msg_send_btn {
  background: #05728f none repeat scroll 0 0;
  border: medium none;
  border-radius: 50%;
  color: #fff;
  cursor: pointer;
  font-size: 17px;
  height: 33px;
  position: absolute;
  right: 0;
  top: 11px;
  width: 33px;
}
.messaging { padding: 0 0 50px 0;}
.msg_history {
  height: 50vh;
  overflow: scroll;

} 
.ming{
  margin-top :50px;
}
.wrap{
  word-wrap: break-word;
}
.b-color{
  background-color: #FFFFF0;
}
</style>
<%= render "devise/shared/header" %>
<div class="b-color">
  <%= render "messages/main_chat" %>
  <%= render "messages/message" %>
</div>
<div class="btn btn-link">
  <%= link_to "ホームに戻る", root_path %>
</div>

app/views/rooms/index.html.erb
<header>
  <div id= "app">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#">DEBATE_APP</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/"><i class="fas fa-home"></i> <span class="sr-only">(current)</span></a>
        </li>
          <li class="nav-item nav-link">
            <%= link_to "検索",search_rooms_path %>
          </li>
        <% if user_signed_in? %>
        <li class="nav-item nav-link">
            <i class="fas fa-sign-in-alt"></i><%= link_to "ログアウト",destroy_user_session_path, method: :delete %>
          </li>

          <li class="nav-item nav-link">
            <%= link_to current_user.nickname, "#" %>
          </li>


        <%else%>
          <li class="nav-item nav-link ">
            <i class="fas fa-sign-in-alt"></i><%= link_to "ログイン",new_user_session_path %>
          </li>
          <li class="nav-item nav-link">
            <i class="fas fa-sign-in-alt"></i><%= link_to "サインイン",new_user_registration_path %>
          </li>
        <%end%>
      </ul>

      <%= search_form_for @q, class: "form-inline my-2 my-lg-0",url:search_rooms_path do |f| %>
      <div class="navbar-brand">Room検索</div>
          
          <i class="fas fa-search mr-3" style="color: royalblue;"></i>
          <%= f.search_field :name_cont, class:"form-control mr-sm-2" %>
          <%= f.submit 'Search',class:"btn btn-secondary my-2 my-sm-0" %>
      <%end%>
    </div>
    </nav>
  </div>
</header>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
<style>
.color-room {
  color: white;
}
.back-color{
  background-color: #f5f5f5;
}
.shadow{
  box-shadow: 4px 4px;
}
.out-width{
  width: 300px;

}
.h-set {
  height:180px;
}
.h-set-auto{
  height :auto ;
}
.h-set-ex{
  height: 50px;
  overflow: scroll;
}
.category {
  width: 90px;
  color: white;
}
.b-color {
  background
}
.wrap{
  word-wrap: break-word;
}
.danger{
  color :red;
}
.date-font {
  font-size: 5px
}
</style>
<main role="main">

  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3"><i class="fas fa-bomb"></i> ディベートをしよう！</h1>
      <p>今すでにあるルームに入ってもらうかまたは自分でお題を作って新規でルームを作ることができます <span class="danger">⚠(サインインしている必要があります)</span></p>

      <div class="btn btn-primary btn-lg" >
      <p><%=link_to 'ルーム作成', new_room_path, class: "color-room" %><i class="fas fa-angle-double-right"></i></p>
      </div>
      <div class="btn btn-dark btn-lg ml-5" >
      <p><a href="#room">ルームに入る<i class="fas fa-angle-double-right"></i></a></p>
      </div>
      <div class="btn btn-primary btn-lg active ml-5" >
      <p><%=link_to '検索',search_rooms_path, class: "color-room" %><i class="fas fa-angle-double-right"></i></p>
      </div>
    </div>
  </div>

  <div class="container marketing b-color">
<% unless user_signed_in? %>
  <div class="alert alert-danger" role="alert">
  ログインしていないと部屋に入れません！ログインしましょう
</div>
<% end %>
<div class="text-center">
  <img src="assets/war.jpg" alt="戦争の画像"width="1100" height="500">
</div>
<h1 id="room" class="text-center">最新の議題</h1>
<div class="row">
    <% if @rooms.length > 0 %>
      <% @rooms.each do |room| %>
      <div class="border border-primary mt-5 out-width ml-3 shadow pt-3">
      <p class="ml-3 date-font">作成日<%= room.created_at.to_s(:datetime_jp) %></p>
        <div class="text-center h-set">
          <%= image_tag room.image.variant(resize: '150x150'), class: 'rounded-circle ' %>
        </div>
        <div class="back-color border border-secondary mb-3 shadow rounded-left ml-5 mr-5" >
          <div class="col text-center h-set-auto">
            <h3 class="ml-3 wrap h-set-ex border-bottom border-dark"><%= room.name%></h3>
            <p class="wrap h-set-ex"><%=room.explanation%></p>
            <p class="bg-secondary category rounded-left">・<%= room.category.name%></p><i class="fas fa-comment-dots"></i><%= room.messages.count %>
            <p><i class="fas fa-door-open"></i><%=link_to "部屋に入る", room_messages_path(room.id), class: "btn btn-primary"%></p>

          </div>
        </div> 
      </div>
      <%end%>
    <% else %>
      <h2 class="text-center">現在議題はありません</h2>
    <%end%>
  </div>
  
  </div>  
  <div class="mt-3">
  <%= paginate @rooms %>
  </div>
</main>

app/views/rooms/new.html.erb
<%= render "devise/shared/header" %>

<style>
.mtoriginal {
  margin-top: 55px;
}
</style>
<div class='container '>
  <h1 class="mtoriginal">新規チャットルーム</h1>
  <%=form_with model: @room,url: rooms_path, local: true do |f|%>
    <%= render 'devise/shared/error_messages', model: f.object %>
    <div class='form-group'>
        <%= f.label :チャットルーム名, class: ' '%><i class="fas fa-signature"></i>
        <%= f.text_field :name, class: 'form-control form-control-lg', placeholder: 'チャットルーム名を入力してください'%>
    </div>
        <div class='form-group'>
        <%= f.label :論点をかいてください。256文字以内, class: ' '%><i class="fas fa-skull-crossbones"></i>
        <%= f.text_area :explanation, class: 'form-control form-control-lg', placeholder: 'チャットルーム名を入力してください'%>
    </div>
    <div class="form-group">
<%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"custom-select d-block w-100", id:"item-category"}) %>
</div>
  <div class="form-group">
<%= f.label :画像%>
    <%= f.file_field :image %>
  </div>
        <%= f.submit "作成", class: 'btn btn-primary'%>

  <% end %>
</div>

app/views/rooms/search.html.erb
<%= render "devise/shared/header" %>
<style>
.color-room {
  color: white;
}
.back-color{
  background-color: #f5f5f5;
}
.shadow{
  box-shadow: 4px 4px;
}
.out-width{
  width: 500px;

}
.h-set {
  height:200px;
}
.h-set-auto{
  height :auto ;
}
.h-set-ex{
  height: 50px;
  overflow: scroll;
}
.category {
  width: 90px;
  color: white;
}
.date-font {
  font-size: 5px
}
.wrap{
  word-wrap: break-word;
}
.danger{
  color :red;
}
</style>
<main role="main">

  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3"><i class="fas fa-bomb"></i> ディベートをしよう！</h1>
      <p>今すでにあるルームに入ってもらうかまたは自分でお題を作って新規でルームを作ることができます<span class="danger">⚠(サインインしている必要があります)</span></p>

      <div class="btn btn-primary btn-lg" >
      <p><%=link_to 'ルーム作成', new_room_path, class: "color-room" %><i class="fas fa-angle-double-right"></i></p>
      </div>
    </div>
  </div>

  <div class="container marketing">
<% unless user_signed_in? %>
  <div class="alert alert-danger" role="alert">
  ログインしていないと部屋に入れません！ログインしましょう
</div>
<% end %>


    <%= search_form_for @q, class: "form-inline my-2 my-lg-0",url:search_rooms_path do |f| %>
    <div class="navbar-brand">Room名検索</div>
        
        <i class="fas fa-search mr-3" style="color: royalblue;"></i>
        <div class="form-group">
          <%= f.search_field :name_cont, class:"form-control mr-sm-2" %>
        </div>

        <%= f.submit 'Search',class:"btn btn-secondary my-2 my-sm-0" %>


    <%end%>
    <%= search_form_for @q, class: "form-inline my-2 my-lg-0",url:search_rooms_path do |f| %>
    <div class="navbar-brand">カテゴリ検索</div>
          <div class="form-group ">
          <i class="fas fa-search mr-3" style="color: royalblue;"></i>
            <%= f.select :category_id_eq, options_from_collection_for_select(Category.all, :id, :name),{class:"custom-select d-block w-100", id:"item-category"} %>
          </div>
          <%= f.submit 'Search',class:"btn btn-secondary my-2 my-sm-0 ml-1" %>
      <%end%>
  <h1 class="text-center mb-3 mt-3">検索結果↓↓</h1>
    <div class="row">
      <% @results.each do |room| %>
     <div class="border border-primary mt-5 out-width ml-3 shadow pt-3">
      <p class="ml-3 date-font">作成日<%= room.created_at.to_s(:datetime_jp) %></p>
      <div class="text-center h-set">
        <%= image_tag room.image.variant(resize: '150x150'), class: 'rounded-circle ' %>
      </div>
      <div class="back-color border border-secondary mb-3 shadow rounded-left ml-5 mr-5" >
        <div class="col text-center h-set-auto">
          <h3 class="ml-3 wrap h-set-ex border-bottom border-dark"><%= room.name%></h3>
          <p class="wrap h-set-ex"><%=room.explanation%></p>
          <p class="bg-secondary category rounded-left">・<%= room.category.name%></p><div class=""><i class="fas fa-comment-dots"></i><%= room.messages.count  %></div>
          <p><i class="fas fa-door-open"></i><%=link_to "部屋に入る", room_messages_path(room.id), class: "btn btn-primary"%></p>

        </div>
      </div> 
    </div>
    <%end%>

    </div>
    </main>